import pandas as pd
from pathlib import Path
import re
import numpy as np
from datetime import datetime, timedelta
import glob
# from pytimeparse.timeparse import timeparse
from pytimeparse2 import parse as timeparse
from .files import *
# import .files as files

class Cme():
	"""
	Class for absorbing coastalME runs into python wrapper
	"""

	def __init__(self, ini=None, run_path=None, ):
		"""Sets up an object to work with a coastalMe run

		Args:
			ini (path, optional): path to cme ini file. Defaults to None.
			run_path (path where cme is run, this is equivalent to the --home command line argument, optional): _description_. Defaults to None.
		"""
		Path.cwd()
		ini = Path(ini)
		self.paths_df, paths = read_ini(ini)
		self.in_path = Path(run_path) / find_var(paths, 'input')
		self.config_df, self.config = read_ini(self.in_path)
		self.out_path = Path(run_path) / find_var(paths, 'output')
		if os.path.exists(self.out_path):
			self.started = True
		else:  
			self.started = False

	def preflight_checks(self, depth=7):
		# Check if output folder exists
		if self.started:
			print("An output folder for this run already exists, CoastalME will overwrite this.")
		# get file list from input
		dir_path = self.in_path.parent
		paths = glob.glob(str(dir_path/"*"))
		files = [fi.split('/')[depth] for fi in paths]
		files_n = [fi.split('.')[0] for fi in files]
		
		# check each file exists
		basement_n = self.find_config('basement').split("/")[-1].split('.')[0]
		if basement_n in files_n:
			basement = True
		elif len(basement_n) < 1:
			basement = False
		else:
			basement = False
		pass


	def find_config(self, query):
		return find_var(self.config, query)
	
	def out_times(self):
		"""Get all the save times intended to be generated by coastalME

		Returns:
			list: list of all save points in simulation time
		"""
		start = find_var(self.config, 'Simulation start date')
		duration = find_var(self.config, 'Duration of simulation')
		t_steps = find_var(self.config, 'Timestep ', case=True)
		steps_p = find_var(self.config, 'save times')


		start = datetime.strptime(start, '%H-%M-%S %m/%d/%Y')
		duration = timedelta(seconds=timeparse(duration))
		end = start + duration
		steps = steps_p.split(' ')
		unit = steps[-1]
		steps = [x+' '+unit for x in steps[0:-1]]
		if len(steps) == 1:
			save_itter = timedelta(seconds=timeparse(steps_p))
			steps = np.arange(start,end,save_itter).astype(datetime).tolist()
			steps.append(end)
			steps.pop(0)
			saves = steps
		else:
			steps = [timedelta(seconds=timeparse(x)) for x in steps]

			saves = [start + x for x in steps]

			saves = [x for x in saves if x <= end]

		return saves
	
	def collate_results(self,vars=['all'],vars_v=['all']):
		# Check if CME has been run
		if not self.started:
			return ValueError("Simulation not run, please run coastalme before using this command")
		path = self.out_path
		# Find expected output save points
		t = self.out_times()
		print("Expected {} timesteps".format(len(t)))
		# using basement outputs, find how many have been produced
		finder = str(path/'basement_elevation*.tif')
		completed = len(glob.glob(finder))
		# Test if we have the expected number of outputs
		if completed == len(t):
			self.success = True
		else:
			# If not we know that cme crashed, save that fact and alter the number of outputs we are looking at
			self.success = False
			crashed = True
			t = t[:completed]
			print("found {} timesteps".format(len(t)))
		# how many different saves are we dealing with
		itters = len(t)
		# If cme crashed, add a fake extra timestep to store the crash outputs
		if crashed:
			delta = t[-1] - t[-2]
			faux = t[-1] + delta
			t.append(faux)
			# t.append(datetime(9999, 9, 9, 0, 0))
		# Now we will collect all the raster and vector files in the output directory
		df = collect_files(itters, path, 'tif')
		df_v = collect_files(itters, path, 'shp')


		# test if the user requested the basement elevation output
		if 'basement_elevation' not in vars:
			# if not, add it as it will be used to define our ncdf extents
			vars.append('basement_elevation')

		# collate all vector outputs into a file
		vectors(t, df_v,path,vars_v)
		# collate all raster outputs into a file
		rasters(t, df,path,vars)
		# Generate plots of any profiles that have been output
		profiles(t, path)

def read_ini(path):
	with open(path, 'r') as f:
		# Get each line from the ini file
		file = f.read().splitlines()
		# Assign numbers to these lines so we can reconstruct
		lines = range(len(file))
		reference = dict(zip(lines, file))
		# save to dataframe
		df = pd.DataFrame(file, index=lines, columns=['string'])
		# Categorise each of the line
		df['type'] = "setting"
		mask = (df.string.str.startswith(';')) | (df.string.str.startswith('#'))
		df.loc[mask, 'type'] = 'comment'
		mask = (df.string == "")
		df.loc[mask, 'type'] = 'blank'

		# now focus on the lines actually containing settings
		mask = (df.type == "setting")
		df['key'] = None
		df['value'] = None
		content = df.loc[mask, "string"]
		df.loc[mask, "key"] = df['string'].map(lambda x: parse_line(x)[0])
		df.loc[mask, "value"] = df['string'].map(lambda x: parse_line(x)[1])
		vars = dict(zip(list(df.loc[mask, "key"].values),list(df.loc[mask, "value"].values)))
	return df, vars

def write_ini(path, df):
	"""This saves any changes to a coastalme input file that have been made

	Args:
		path (string): save path (including file name)
		df (pandas dataframe): dataframe in format read from template file, any changed settings in key, value column are incorporated
	"""
	changed = (~df.key.isnull())
	df.loc[changed, 'string'] = (df.loc[changed, 'key']+' : '+ df.loc[changed, 'value'])
	out_lines = df['string'].to_list()
	with open(str(path), mode='wt', encoding='utf-8') as f:
		f.write('\n'.join(out_lines))

def parse_line(in_str):
	split = in_str.partition(':')
	split = [x.strip() for x in split]
	split = [x for x in split if not x==':']
	split = [re.sub(' +', ' ', x) for x in split]
	return split


def find_var(dict, query, case=False):
		if case:
			results = {key: val for key, val in dict.items() if re.search(query, key)}
		else:
			results = {key: val for key, val in dict.items() if re.search(query, key, re.I)}
		if len(results) == 0:
			raise KeyError('No matches for: {}'.format(query))
		if len(results) != 1:
			raise KeyError('Multiple matches for variable in input file: {}'.format(list(results.keys())))
		
		out = next(iter(results.values()))

		if ';' in out:
			out = out.partition(';')[0]
		
				
		return out 

